layout_spectrum: 0.6207037
typography_spectrum: 0.7862996
color:
  saturation: 0.897326
  lightness: 0.7862477
  brandStrength: 0.675702
  rhythmicContrast: 0.8293752
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Cherry Spoon Collective
