name: Cherry Spoon Collective
favicon: null
layout_spectrum: 0.74622
typography_spectrum: 0.08297873
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#15161F'
    - '#B38904'
    - '#3988B4'
    - '#A390A4'
    - '#164B6E'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
